# Kubernetes MCP Server Configuration

server:
  # Server binding settings
  bind_ip: "10.121.87.184"  # Bind to all interfaces
  bind_port: 8080     # Default port
  mode: "network"       # "network" or "stdio"

kubernetes:
  # Path to kubeconfig file
  # If null, uses the default kubeconfig path
  kubeconfig_path: null

logging:
  # Logging settings
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: null     # Path to log file, or null to log to stderr only
