apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-k8s-server
  labels:
    app: mcp-k8s-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-k8s-server
  template:
    metadata:
      labels:
        app: mcp-k8s-server
    spec:
      serviceAccountName: mcp-k8s-server
      containers:
      - name: mcp-k8s-server
        image: dockerrepo:30500/mcp-k8s-server:1.1
        imagePullPolicy: IfNotPresent
        command:
        - python
        - -m
        - mcp_k8s_server.main
        args:
        - --transport
        - sse
        - --port
        - "8000"
        - --host
        - "0.0.0.0"
        - --config
        - "/app/config/config.yaml"
        - --debug
        ports:
        - containerPort: 8000
          name: http
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 65534
          runAsNonRoot: true
          runAsUser: 65534
          seccompProfile:
            type: RuntimeDefault
      volumes:
      - name: config-volume
        configMap:
          name: mcp-k8s-server-config
