# Copyright (c) 2025, Lewis Guo. All rights reserved.
# Author: Lewis Guo <guolisen@gmail.com>
# Created: April 05, 2025
#
# Description: YAML configuration for the MCP Kubernetes server: deployment.yaml
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-k8s-server
  labels:
    app: mcp-k8s-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-k8s-server
  template:
    metadata:
      labels:
        app: mcp-k8s-server
    spec:
      serviceAccountName: mcp-k8s-server
      containers:
      - name: mcp-k8s-server
        image: guolisen/mcp-k8s-server:2.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: TRANSPORT
          value: "sse"
        - name: PORT
          value: "8000"
        - name: HOST
          value: "0.0.0.0"
        - name: CONFIG_PATH
          value: "/app/config/config.yaml"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 65534
          runAsNonRoot: true
          runAsUser: 65534
          seccompProfile:
            type: RuntimeDefault
      volumes:
      - name: config-volume
        configMap:
          name: mcp-k8s-server-config
