apiVersion: v1
kind: Service
metadata:
  name: mcp-k8s-server
  labels:
    app: mcp-k8s-server
spec:
  selector:
    app: mcp-k8s-server
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  type: NodePort
