# Copyright (c) 2025, Lewis Guo. All rights reserved.
# Author: Lewis Guo <guolisen@gmail.com>
# Created: April 05, 2025
#
# Description: YAML configuration for the MCP Kubernetes server: service.yaml
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

apiVersion: v1
kind: Service
metadata:
  name: mcp-k8s-server
  labels:
    app: mcp-k8s-server
spec:
  selector:
    app: mcp-k8s-server
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  type: NodePort
