# Copyright (c) 2025, Lewis Guo. All rights reserved.
# Author: Lewis Guo <guolisen@gmail.com>
# Created: April 05, 2025
#
# Description: YAML configuration for the MCP Kubernetes server: config.yaml
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# MCP Kubernetes Server Configuration

server:
  name: mcp-k8s-server
  transport: sse  # stdio or sse
  port: 8000
  host: 0.0.0.0

kubernetes:
  # Path to kubeconfig file
  # If empty, will try to use in-cluster config when running in Kubernetes
  # or ~/.kube/config; /etc/rancher/rke2/rke2.yaml when running locally
  config_path: ""
  
  # Kubernetes context to use
  # If empty, will use the current context from kubeconfig
  context: ""
  
  # Default namespace
  namespace: default
  
  # Resource types to include
  resource_types:
    - pods
    - deployments
    - services
    - configmaps
    - secrets
    - persistentvolumeclaims
    - persistentvolumes
    - nodes
    - namespaces
    - events
    - ingresses
    - statefulsets
    - daemonsets
    - jobs
    - cronjobs
    - replicasets

monitoring:
  # Enable monitoring features
  enabled: true
  
  # Polling interval in seconds
  interval: 30
  
  # Resources to monitor
  resources:
    - pods
    - nodes
    - deployments
    - volume
    
  # Metrics to collect
  metrics:
    - cpu
    - memory
    - disk
    - network
